<?php
/**
 * Password Reset Page — Spencer's Website v7.0
 * Handles token-based password reset generated by admin
 */
require_once __DIR__ . '/includes/init.php';

$token = $_GET['token'] ?? '';
$error = '';
$success = false;

// Generate CSRF token for this form
if (empty($_SESSION['csrf_token'])) {
    $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
}

if ($token) {
    try {
        require_once 'config/database.php';
        $database = new Database();
        $db = $database->getConnection();

        // Ensure table exists
        $db->exec("CREATE TABLE IF NOT EXISTS password_resets (
            id INT AUTO_INCREMENT PRIMARY KEY,
            user_id INT NOT NULL,
            token VARCHAR(64) NOT NULL,
            expires_at TIMESTAMP NOT NULL,
            used_at TIMESTAMP NULL,
            created_by INT NULL,
            INDEX idx_token (token),
            INDEX idx_user (user_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

        // Validate token
        $stmt = $db->prepare("SELECT pr.*, u.username FROM password_resets pr JOIN users u ON pr.user_id = u.id WHERE pr.token = ? AND pr.used_at IS NULL AND pr.expires_at > NOW()");
        $stmt->execute([$token]);
        $reset = $stmt->fetch(PDO::FETCH_ASSOC);

        if (!$reset) {
            $error = 'This reset link is invalid or has expired.';
        } elseif ($_SERVER['REQUEST_METHOD'] === 'POST') {
            // CSRF check
            $postCsrf = $_POST['csrf_token'] ?? '';
            if ($postCsrf !== $_SESSION['csrf_token']) {
                $error = 'Security token mismatch. Please try again.';
            } else {
                $newPassword = $_POST['password'] ?? '';
                $confirmPassword = $_POST['password_confirm'] ?? '';

                if (strlen($newPassword) < 8) {
                    $error = 'Password must be at least 8 characters.';
                } elseif ($newPassword !== $confirmPassword) {
                    $error = 'Passwords do not match.';
                } else {
                    $hash = password_hash($newPassword, PASSWORD_DEFAULT);
                    $stmt = $db->prepare("UPDATE users SET password = ? WHERE id = ?");
                    $stmt->execute([$hash, $reset['user_id']]);

                    // Mark token as used
                    $stmt = $db->prepare("UPDATE password_resets SET used_at = NOW() WHERE id = ?");
                    $stmt->execute([$reset['id']]);

                    // Invalidate all other reset tokens for this user
                    $stmt = $db->prepare("UPDATE password_resets SET used_at = NOW() WHERE user_id = ? AND used_at IS NULL");
                    $stmt->execute([$reset['user_id']]);

                    $success = true;
                }
            }
        }
    } catch (Exception $e) {
        $error = 'An error occurred. Please try again.';
    }
} else {
    $error = 'No reset token provided.';
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Password — Spencer's Website</title>
    <link rel="icon" href="/assets/images/favicon.webp">
    <link rel="stylesheet" href="css/tokens.css">
    <style>
        *, *::before, *::after { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #04040A; color: #E2E8F0; display: flex; align-items: center; justify-content: center; min-height: 100vh; }
        .container { max-width: 400px; width: 100%; padding: 24px; }
        .card { background: rgba(255,255,255,0.04); border: 0.5px solid rgba(255,255,255,0.10); backdrop-filter: blur(20px); border-radius: 20px; padding: 32px; }
        h1 { font-size: 1.5rem; font-weight: 400; margin-bottom: 8px; }
        p { font-size: 0.9rem; color: #94a3b8; margin-bottom: 20px; }
        .form-group { margin-bottom: 16px; }
        label { display: block; font-size: 12px; font-weight: 500; color: #64748B; margin-bottom: 6px; text-transform: uppercase; letter-spacing: 0.05em; }
        input { width: 100%; padding: 10px 14px; background: rgba(255,255,255,0.03); border: 0.5px solid rgba(255,255,255,0.10); border-radius: 8px; color: #E2E8F0; font-size: 14px; }
        input:focus { outline: none; border-color: #7B6EF6; box-shadow: 0 0 0 3px rgba(123,110,246,0.1); }
        button { width: 100%; padding: 12px; background: #7B6EF6; border: none; border-radius: 8px; color: #fff; font-size: 14px; font-weight: 500; cursor: pointer; }
        button:hover { background: #6B5EE6; }
        .error { color: #F87171; font-size: 13px; margin-bottom: 12px; }
        .success { color: #1DFFC4; font-size: 13px; margin-bottom: 12px; }
        a { color: #7B6EF6; text-decoration: none; }
    </style>
</head>
<body>
<div class="container">
    <div class="card">
        <h1>Reset Password</h1>
        <?php if ($success): ?>
            <p class="success">Your password has been reset successfully.</p>
            <p><a href="index.php">Return to login</a></p>
        <?php elseif ($error): ?>
            <p class="error"><?= htmlspecialchars($error) ?></p>
            <?php if (!$token || !$reset): ?>
            <p><a href="index.php">Return to login</a></p>
            <?php endif; ?>
        <?php endif; ?>

        <?php if (!$success && isset($reset) && $reset): ?>
        <p>Resetting password for <strong><?= htmlspecialchars($reset['username']) ?></strong></p>
        <form method="POST">
            <input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token']) ?>">
            <div class="form-group">
                <label>New Password</label>
                <input type="password" name="password" required minlength="8" autocomplete="new-password">
            </div>
            <div class="form-group">
                <label>Confirm Password</label>
                <input type="password" name="password_confirm" required minlength="8" autocomplete="new-password">
            </div>
            <button type="submit">Reset Password</button>
        </form>
        <?php endif; ?>
    </div>
</div>

    <?php require __DIR__ . '/includes/site_footer.php'; ?>
</body>
</html>
